name: znny_manager
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  google_fonts: ^3.0.1
  flutter_lints: ^2.0.1
  flutter_spinkit: ^5.1.0
  sp_util: ^2.0.3
  eva_icons_flutter: ^3.0.2
  connectivity_plus: ^2.2.0
  fluttertoast: ^8.1.2
  flutter_svg: ^1.0.3
  fl_chart: ^0.55.0
  provider: ^6.0.1
  data_table_2: ^2.2.3
  syncfusion_flutter_datagrid: ^20.1.57
  adaptive_theme: ^3.0.0
  flutter_easyloading: ^3.0.5
  http: ^0.13.4
  dio: ^4.0.4
  pull_to_refresh: ^2.0.0
  file_picker: ^4.6.0
  intl: ^0.17.0
  get: ^4.6.5
  cached_network_image: ^3.2.1
  percent_indicator: ^4.2.2
  html_editor_enhanced: ^2.5.0
  flutter_staggered_grid_view: ^0.6.2


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/raster/
    - assets/icons/
